export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// GLOBAL
export const BEGIN = "BEGIN";
export const DONE = "DONE";
export const SUCCESS = "SUCCESS";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";

// 
export const ASYNC_REQ_BEGIN = "ASYNC_REQ_BEGIN";
export const GET_DATA_SUCESS = "GET_DATA_SUCESS";
export const SET_MERCHANT_PROFILE = "SET_MERCHANT_PROFILE";
export const ASYNC_SUCCESS = "ASYNC_SUCCESS";

export const GET_PACKETS_BEGIN = "GET_PACKETS_BEGIN";
export const GET_PACKETS_SUCCESS = "GET_PACKETS_SUCCESS";

export const GET_CUSTOMERS_BEGIN = "GET_CUSTOMERS_BEGIN";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";

export const GET_PACKET_BEGIN = "GET_PACKET_BEGIN";
export const GET_PACKET_SUCCESS = "GET_PACKET_SUCCESS";
export const CLEAR_PACKET = "CLEAR_PACKET";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const CLEAR_PACKET_VALUES = "CLEAR_PACKET_VALUES";
export const CLEAR_USER_VALUES = "CLEAR_USER_VALUES";

export const SET_AREA_BEGIN = "SET_AREA_BEGIN";
export const SET_AREA = "SET_AREA";
export const SET_AREA_SUCCESS = "SET_AREA_SUCCESS";

export const ADD_PACKET_BEGIN = "ADD_PACKET_BEGIN";
export const ADD_PACKET_SUCCESS = "ADD_PACKET_SUCCESS";

export const SET_EDIT_PACKET = "SET_EDIT_PACKET";
export const EDIT_PACKET_BEGIN = "EDIT_PACKET_BEGIN";
export const EDIT_PACKET_SUCCESS = "EDIT_PACKET_SUCCESS";


export const EDIT_STATUS_BEGIN = "EDIT_STATUS_BEGIN";
export const EDIT_STATUS_SUCCESS = "EDIT_STATUS_SUCCESS";


export const GET_ALL_MERCHANT_SUCCESS = "GET_ALL_MERCHANT_SUCCESS";

export const SET_EDIT_MERCHANT = "SET_EDIT_MERCHANT";
export const EDIT_MERCHANT_BEGIN = "EDIT_MERCHANT_BEGIN";
export const EDIT_MERCHANT_SUCCESS = "EDIT_MERCHANT_SUCCESS";

export const GET_MERCHANT_BEGIN = "GET_MERCHANT_BEGIN";
export const GET_MERCHANT_SUCCESS = "GET_MERCHANT_SUCCESS";

export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";


export const ADD_USER_BEGIN = "ADD_USER_BEGIN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const SET_EDIT_USER = "SET_EDIT_USER";
export const EDIT_USER_BEGIN = "EDIT_USER_BEGIN";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";


export const GET_AGENT_BEGIN = "GET_AGENT_BEGIN";
export const GET_AGENT_SUCCESS = "GET_AGENT_SUCCESS";

export const RESET_FILTER = "RESET_FILTER";

export const CREATE_INVOICES_BEGIN = "CREATE_INVOICES_BEGIN";
export const CREATE_INVOICES_SUCCESS = "CREATE_INVOICES_SUCCESS";

export const GET_INVOICES_BEGIN = "GET_INVOICES_BEGIN";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";

export const SET_EDIT_INVOICE = "SET_EDIT_INVOICE";
export const UPDATE_INVOICE_BEGIN = "UPDATE_INVOICE_BEGIN";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";

export const GET_INVOICE_BEGIN = "GET_INVOICE_BEGIN";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";

export const GET_STATS_BEGIN = "GET_STATS_BEGIN";
export const SET_STATS = "SET_STATS";
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";

export const FILTER_PACKET_BEGIN = "FILTER_PACKET_BEGIN";

export const FILTER_PACKET_DELIVERY = "FILTER_PACKET_DELIVERY";
export const FILTER_PACKET_DELIVERED = "FILTER_PACKET_DELIVERED";
export const FILTER_PACKET_RETURNED = "FILTER_PACKET_RETURNED";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";